### ISSUE TITLE
Linking fails on debian jessie, wxWidgets 2.8.12

### ISSUE THREAD

**Issue by RomanHargrave** [audacity/audacity#61]
I have a suspicion that this has to do with linker flag order.

When building `HEAD`, all goes well until the linker is invoked.

OOPS!!!  I had no idea I could edit the comments from someone else.  I thought I was replying.  Sorry about that Roman.

**Comment by JamesCrook** [comment]
Windows developer guessing the problem might possibly be a 3.x include file being mistakenly used by source in the lib-src/FileDialog subdirectory (a makefile in that directory not updated).  Anyway this is a WONTFIX as the current development version of Audacity for release as 2.1.2 has shifted to wx3.0.2,  If you try compiling the current HEAD version with Jessie that would help us.

**Comment by lllucius** [comment]
Here's where I SHOULD have added my comment...

This is interesting.  You shouldn't have been able to even get past configure if you were trying to use wxWidgets 2.8.x.  I've updated configure to specifically look for wxWidgets 3.0.x.

Would you mind sharing your config.log?

**Comment by RomanHargrave** [comment]
On Fri, 28 Aug 2015 15:28:55 -0700
Leland Lucius <notifications@github.com> wrote:

> Here's where I SHOULD have added my comment...
> 
> This is interesting.  You shouldn't have been able to even get past configure if you were trying to use wxWidgets 2.8.x.  I've updated configure to specifically look for wxWidgets 3.0.x.
> 
> Would you mind sharing your config.log?
> 
> 
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/audacity/audacity/issues/61#issuecomment-135902109

If I still have it, though this was pre-3.0-transition. I will try rebuilding tonight.

-- 
Roman Hargrave <roman@hargrave.info> 
 http://hargrave.info 

 _________________________________
< New crypt. See /usr/news/crypt. >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by RomanHargrave** [comment]
On Fri, 28 Aug 2015 14:29:58 -0700
James Crook <notifications@github.com> wrote:

> Windows developer guessing the problem might possibly be a 3.x include file being mistakenly used by source in the lib-src/FileDialog subdirectory (a makefile in that directory not updated).  Anyway this is a WONTFIX as the current development version of Audacity for release as 2.1.2 has shifted to wx3.0.2,  If you try compiling the current HEAD version with Jessie that would help us.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/audacity/audacity/issues/61#issuecomment-135892958

I tried compiling the current HEAD today (f5f436a), and ran in to the following error during compilation:

```
g++ -DHAVE_CONFIG_H -I.  -Wno-deprecated-declarations -D__STDC_CONSTANT_MACROS -DLIBDIR=\"/usr/local//lib\"   -I../lib-src/portaudio-v19/include    -I../lib-src/lib-widget-extra -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread          -I../lib-src/libnyquist -I/usr/include/soundtouch    -I../lib-src/lv2/include -I../lib-src/lv2/include -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -Wall -I/usr/include/portSMF      -I/usr/lib/x86_64-linux-gnu/wx/include/gtk2-unicode-3.0 -I/usr/include/wx-3.0 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/gio-unix-2.0/ -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/libpng12 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2  -Wno-unused-local-typedefs -I../lib-src/portmixer/include -mmmx -msse -msse2 -msse3 -march=native -mtune=native -O3 -fexpensive-optimizations -DwxDEBUG_LEVEL=0  -Wall -I../include -I../lib-src/FileDialog                   -MT audacity-AudacityApp.o -MD -MP -MF .deps/audacity-AudacityApp.Tpo -c -o audacity-AudacityApp.o `test -f 'AudacityApp.cpp' || echo './'`AudacityApp.cpp
In file included from AudacityApp.cpp:73:0:
FFmpeg.h: In function ‘AVOutputFormat* av_oformat_next(AVOutputFormat*)’:
FFmpeg.h:692:25: error: conflicting declaration of C function ‘AVOutputFormat* av_oformat_next(AVOutputFormat*)’
       (AVOutputFormat *f),
                         ^
FFmpeg.h:486:18: note: in definition of macro ‘FFMPEG_FUNCTION_WITH_RETURN’
       inline r n a                                                      \
                  ^
In file included from FFmpeg.h:44:0,
                 from AudacityApp.cpp:73:
/usr/include/libavformat/avformat.h:1827:17: note: previous declaration ‘AVOutputFormat* av_oformat_next(const AVOutputFormat*)’
 AVOutputFormat *av_oformat_next(const AVOutputFormat *f);
                 ^
In file included from AudacityApp.cpp:73:0:
FFmpeg.h: In function ‘int av_fifo_size(AVFifoBuffer*)’:
FFmpeg.h:759:23: error: conflicting declaration of C function ‘int av_fifo_size(AVFifoBuffer*)’
       (AVFifoBuffer *f),
                       ^
FFmpeg.h:486:18: note: in definition of macro ‘FFMPEG_FUNCTION_WITH_RETURN’
       inline r n a                                                      \
                  ^
In file included from FFmpeg.h:45:0,
                 from AudacityApp.cpp:73:
/usr/include/libavutil/fifo.h:76:5: note: previous declaration ‘int av_fifo_size(const AVFifoBuffer*)’
 int av_fifo_size(const AVFifoBuffer *f);
     ^
In file included from AudacityApp.cpp:73:0:
FFmpeg.h: In function ‘AVDictionaryEntry* av_dict_get(AVDictionary*, const char*, const AVDictionaryEntry*, int)’:
FFmpeg.h:805:82: error: conflicting declaration of C function ‘AVDictionaryEntry* av_dict_get(AVDictionary*, const char*, const AVDictionaryEntry*, int)’
       (AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags),
                                                                                  ^
FFmpeg.h:486:18: note: in definition of macro ‘FFMPEG_FUNCTION_WITH_RETURN’
       inline r n a                                                      \
                  ^
In file included from /usr/include/libavcodec/avcodec.h:37:0,
                 from FFmpeg.h:43,
                 from AudacityApp.cpp:73:
/usr/include/libavutil/dict.h:104:20: note: previous declaration ‘AVDictionaryEntry* av_dict_get(const AVDictionary*, const char*, const AVDictionaryEntry*, int)’
 AVDictionaryEntry *av_dict_get(const AVDictionary *m, const char *key,
                    ^
```


-- 
Roman Hargrave <roman@hargrave.info> 
 http://hargrave.info 

 ________________________________________
< Crazee Edeee, his prices are INSANE!!! >
 ----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

**Comment by JamesCrook** [comment]
The same snapshot builds on ubuntu 4.6.3.
https://travis-ci.org/audacity/audacity/builds/77838416


You could try 
./configure --with-ffmpeg=local
To build with the FFmpeg src that comes with Audacity.
(Version 2.2.2-1 according to headers)



FFmpeg 2.5 (and probably later too) requires this patch.  We've not tested with this version of FFmpeg:

--- a/src/FFmpeg.h	2015-02-21 00:33:33.853857529 +0100
+++ b/src/FFmpeg.h	2015-02-21 00:35:09.626497205 +0100
@@ -688,7 +688,7 @@
    FFMPEG_FUNCTION_WITH_RETURN(
       AVOutputFormat*,
       av_oformat_next,
-      (AVOutputFormat *f),
+      (const AVOutputFormat *f),
       (f)
    );
    FFMPEG_FUNCTION_WITH_RETURN(
@@ -755,7 +755,7 @@
    FFMPEG_FUNCTION_WITH_RETURN(
       int,
       av_fifo_size,
-      (AVFifoBuffer *f),
+      (const AVFifoBuffer *f),
       (f)
    );
    FFMPEG_FUNCTION_WITH_RETURN(
@@ -801,7 +801,7 @@
    FFMPEG_FUNCTION_WITH_RETURN(
       AVDictionaryEntry *,
       av_dict_get,
-      (AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags),
+      (const AVDictionary *m, const char *key, const AVDictionaryEntry *prev, int flags),
       (m, key, prev, flags)
    );
    FFMPEG_FUNCTION_WITH_RETURN(

**Comment by RomanHargrave** [comment]
Looks like it compiled after that.

**Comment by JamesCrook** [comment]
Thanks.  I'm assuming 'that' refers to the configure switch, not the patch.

Closing the issue.

**Comment by RomanHargrave** [comment]
Correct.
