### ISSUE TITLE
Audacity 3.7.5 fails to build on RHEL8.10

### ISSUE THREAD

**Issue by sjwhitak** [audacity/audacity#9248]
### Bug description

I'm trying to build Audacity 3.7.5 on RHEL8.10 and I received two errors:

```error
In file included from /opt/audacity-3.7.5/libraries/lib-math/tests/MathTests.cpp:11:
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h: In function ‘std::pair<double, double> LinearFit(const std::vector<X>&, const std::vector<Y>&, std::vector<W>)’:
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:41:47: error: ‘plus’ is not a member of ‘std’
       x.begin(), x.end(), y.begin(), 0., std::plus<>(),
                                               ^~~~
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:41:52: error: expected primary-expression before ‘>’ token
       x.begin(), x.end(), y.begin(), 0., std::plus<>(),
                                                    ^
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:41:54: error: expected primary-expression before ‘)’ token
       x.begin(), x.end(), y.begin(), 0., std::plus<>(),
                                                      ^
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:46:47: error: ‘plus’ is not a member of ‘std’
       x.begin(), x.end(), x.begin(), 0., std::plus<>(),
                                               ^~~~
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:46:52: error: expected primary-expression before ‘>’ token
       x.begin(), x.end(), x.begin(), 0., std::plus<>(),
                                                    ^
/opt/audacity-3.7.5/libraries/lib-math/LinearFit.h:46:54: error: expected primary-expression before ‘)’ token
       x.begin(), x.end(), x.begin(), 0., std::plus<>(),

```

After adding `#include <iostream>` into [LinearFit.h](https://github.com/audacity/audacity/blob/release-3.7.5/libraries/lib-math/LinearFit.h), this solved this issue and I could continue building.

The second issue I received is:

```bash
In file included from /usr/include/c++/8/memory:80,
                 from /opt/audacity-3.7.5/libraries/lib-theme/AColor.h:17,
                 from /opt/audacity-3.7.5/src/AudacityHeaders.h:43,
                 from /opt/audacity-3.7.5/build/src/CMakeFiles/Audacity.dir/cmake_pch.hxx:6,
                 from <command-line>:
/usr/include/c++/8/bits/unique_ptr.h: In instantiation of ‘void std::default_delete<_Tp>::operator()(_Tp*) const [with _Tp = WaveClipAdjustBorderHandle::AdjustPolicy]’:
/usr/include/c++/8/bits/unique_ptr.h:277:17:   required from ‘std::unique_ptr<_Tp, _Dp>::~unique_ptr() [with _Tp = WaveClipAdjustBorderHandle::AdjustPolicy; _Dp = std::default_delete<WaveClipAdjustBorderHandle::AdjustPolicy>]’
/opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/WaveClipAdjustBorderHandle.h:30:49:   required from here
/usr/include/c++/8/bits/unique_ptr.h:79:16: error: invalid application of ‘sizeof’ to incomplete type ‘WaveClipAdjustBorderHandle::AdjustPolicy’
  static_assert(sizeof(_Tp)>0,
                ^~~~~~~~~~~
In file included from /opt/audacity-3.7.5/libraries/lib-track/ChannelAttachments.h:16,
                 from /opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/../../../ui/CommonTrackPanelCell.h:15,
                 from /opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/../../../ui/ChannelView.h:15,
                 from /opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/../../../ui/CommonChannelView.h:14,
                 from /opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/WaveChannelView.h:14,
                 from /opt/audacity-3.7.5/src/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp:11:
/opt/audacity-3.7.5/libraries/lib-track/Track.h:647:23: warning: inline function ‘bool operator!=(TrackIter<const Track>, TrackIter<const Track>)’ used but never defined
    friend inline bool operator != (TrackIter a, TrackIter b)
                       ^~~~~~~~
make[2]: *** [src/CMakeFiles/Audacity.dir/build.make:4861: src/CMakeFiles/Audacity.dir/tracks/playabletrack/wavetrack/ui/WaveChannelView.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:6443: src/CMakeFiles/Audacity.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```
Now, it seems to be another `#include "WaveClipAdjustBorderHandle.h` is missing [from my measley searching online](https://stackoverflow.com/questions/8915230/), but I'm unable to figure out where I need to put this.

I'm also interested as to how, when I compile Audacity on Debian at home, I have none of these issues, but on RHEL8.10 at work, I do. 

### Steps to reproduce

```
wget https://github.com/audacity/audacity/archive/refs/tags/Audacity-3.7.5.tar.gz
tar xzf Audacity.3.7.5.tar.gz
cd audacity-Audacity-3.7.5
mkdir build && cd build
cmake -G "Unix Makefiles" ../
make -j1
```

### Expected behavior

It builds successfully.

### Audacity Version

Audacity 3.7.5

### Operating system

Linux

**Comment by kryksyh** [comment]
@sjwhitak, could you share what compiler you use?

**Comment by sjwhitak** [comment]
> We use GCC 9 and later, but any C++17 compliant compiler should work.

I use gcc `8.5.0` unfortunately with RHEL8, https://access.redhat.com/solutions/19458

```
cmake -G "Unix Makefiles" ../
-- The C compiler identification is GNU 8.5.0
-- The CXX compiler identification is GNU 8.5.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /opt/envs/test/bin/python3.11 (found version "3.11.13") found components: Interpreter 
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
-- Build Info:
--   Host System: Linux-4.18.0-553.66.1.el8_10.x86_64
--   Host System Name: Linux
--   Host System Processor: x86_64
--   Host System Version: 4.18.0-553.66.1.el8_10.x86_64
--   Host System Architecture: 64-bit
-- 
--   Compiler: /usr/bin/c++
--   Compiler Version: 8.5.0
--   Compiler Standard: 17
--   Compiler Standard Required: ON
--   Compiler Extensions: 
-- 
--   Current Commit: unknown
```
