### ISSUE TITLE
Build issues with audacity 3.0.3

### ISSUE THREAD

**Issue by timtas** [audacity/audacity#1428]
**audacity (conan) fails to set proper CFLAGS and LIBS**

When trying to build audacity 3.0.3 from source, got into some trouble to get conan setting the right CFLAGS / LIBS for gtk2 / wxwidgets. This was not the case in 3.0.2, so I would call this a bug.

**To Reproduce**

As with 3.0.2, I did:

1. Unpack the source
2. Typed:
`mkdir build
cd build || exit
`
3. As per instruction, called:
`cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/X11 -DCFGDIR=/etc -Daudacity_use_ffmpeg=loaded -Daudacity_use_sqlite=local -Daudacity_obey_system_dependencies=On -Daudacity_use_wxwidgets=system ..`

4. Typed make

The build then started, until it then failed to find the gtk2 and wxwidgets libraries.

This may  be due to the fact that I have gtk2 and wxwidgets (and all other x11 stuff) in /opt/X11, however this worked fine with 3.0.2. As my wx-config is setup correctly, I could finally work around the problem by calling:

`CFLAGS=$(wx-config --cflags)`
`CXXFLAGS=$(wx-config --cxxflags)`
`CPPCLAGS=$(wx-config --cppflags)`
`LDLIBS=$(wx-config --libs)`
`LDFLAGS=$LDLIBS`
`export CFLAGS CXXFLAGS CPPCLAGS LDFLAGS LDLIBS`

before cmake. But I think, cmake/conan or whoever should do this for my, as it was the case in 3.0.2.

**Comment by crsib** [comment]
Can you please specify your OS? Is wx-config in path? Building against preinstalled wx works fine on Fedora, so we need more details to reproduce the issue.

Can you provide the build log? Given that you've managed to get past the cmake - wxWidgets were found successfully.

**Comment by timtas** [comment]
I have attached my build log, as you can see, it fails to build lib-string-utils due to not finding wx/string.h.

My OS is a self-built LFS system, with all X11/GTK/WX stuff installed in /opt/X11, so clearly nothing you should worry about too much.

But my setup usually works for most software packages that depend on pkg-config, or in this case, a standalone wx-config script, and it worked in 3.0.2. So, I assume that this new conan thing does either not call wx-config correctly, or does not use its output for building the needed packages.

I managed to work around this by my described work-around of calling wx-config and setting CFLAGS, CXXFLAGS, CPPFLAGS,LDLIBS and LDFLAGS before calling cmake.




[audacity-build.log](https://github.com/audacity/audacity/files/6934470/audacity-build.log)

**Comment by crsib** [comment]
Thank you a lot, I will look into

**Comment by timtas** [comment]
Btw: If you want me to test some patch for this, I will happily do that.

**Comment by crsib** [comment]
Just out of curiosity, does it help deleting `cmake-proxies/cmake-modules/FindwxWidgets.cmake`?

**Comment by timtas** [comment]
No, sadly, it doesnt:
`removed 'cmake-proxies/cmake-modules/FindwxWidgets.cmake'
++ cmake -G 'Unix Makefiles' -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/opt/X11 -DCFGDIR=/etc -Daudacity_use_ffmpeg=loaded -Daudacity_use_sqlite=local -Daudacity_obey_system_dependencies=On -Daudacity_use_wxwidgets=system ..
`

It then still ends with:

```In file included from /lgl-bld/audacity-Audacity-3.0.3/libraries/lib-string-utils/CodeConversions.cpp:11:
/lgl-bld/audacity-Audacity-3.0.3/libraries/lib-string-utils/CodeConversions.h:14:10: fatal error: wx/string.h: No such file or directory
   14 | #include <wx/string.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[2]: *** [libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/build.make:104: libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/CodeConversions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1257: libraries/lib-string-utils/CMakeFiles/lib-string-utils.dir/all] Error 2
make: *** [Makefile:156: all] Error 2

```

**Comment by crsib** [comment]
I've tried reproducing the environment, but Audacity compiles just fines :(

Can you please post the output of:
```
wx-config --list
wx-config --cflags  --libs
```

**Comment by timtas** [comment]
```
timtas@lfsda0:~/src$ wx-config --list

    Default config is gtk2-unicode-3.1

  Default config will be used for output

timtas@lfsda0:~/src$ wx-config --cflags  --libs
-I/opt/X11/lib/wx/include/gtk2-unicode-3.1 -I/opt/X11/include/wx-3.1 -D_FILE_OFFSET_BITS=64 -DWXUSINGDLL -D__WXGTK__ -pthread
-L/opt/X11/lib -pthread   -lwx_gtk2u_xrc-3.1 -lwx_gtk2u_html-3.1 -lwx_gtk2u_qa-3.1 -lwx_gtk2u_core-3.1 -lwx_baseu_xml-3.1 -lwx_baseu_net-3.1 -lwx_baseu-3.1 
```
