### PR TITLE
Audacity fails to compile with VS2019 16.9.0 (lrint, lrintf)

### PR DESCRIPTION
**Pull request by JohnColket**
While prior releases of Windows VS2019 seemed to work with the new build instructions (see prior pull request), the very latest release 16.9.0 of VS2019, seems to have a problem with the intrinsic functions lrint and lrintf, and generates 68 compile errors.
Specifically, the build fails with an error: error C2169: 'lrint': intrinsic function, cannot be defined
and error C2169: 'lrintf': intrinsic function, cannot be defined while compiling AudioIO.cpp and other modules.

This patch removes the lrint and lrintf definitions using conditional compilation instructions depending on the value of "_MSC_VER".  I am sure there are other, perhaps more valid, approaches.

Note: the value of _MSC_VER is 1928 in 16.9.0. (_MSC_VER is also 1928 in 16.8.0, but _MSC_VER is 1927 in 16.7.0)
_MSC_FULL_VER happens to be 192829910 in my copy of 16.9.0, which has the problem.

I do not have _MSC_VER numbers of all prior successful Audacity builds, but it is reported that 16.3.8 builds OK (corresponding to _MSC_VER of 1923).  See this forum report: https://forum.audacityteam.org/viewtopic.php?p=418872#p418872

### CODE REVIEW

**Comment by DavidBailes** [comment]
I don't have this problem compiling with 16.9.0 - it compiles without errors.

**Comment by JohnColket** [comment]
Thanks for this report, David.  Very curious....  I'll take a look-see...

- John

**Comment by JohnColket** [comment]
So I uninstalled VS2019, then reinstalled it.  I still have the issue.  I
had been suspecting there might be micro versions of 16.9.0, so I checked
and found that _MSC_FULL_VER is still 192829910 which is what it was
yesterday.  I don't know if there is any way for me to download a prior
version of VS2019.

**Comment by DavidBailes** [comment]
The suggested fix of removing the inline definitions of lrint and lrintf reintroduces bug 2457.

An alternative fix, is in the #if (defined (WIN32) || defined (_WIN32)) && defined(_MSC_VER) && defined(_M_IX86) statement, to add the following line before the inline definitions:

#pragma function(lrint,lrintf)   // do not use intrinsic versions

I'm not sure if the inclusion of this line needs to depend on the version of the compiler.

**Comment by JohnColket** [comment]
David,

Thank you very much for your discoveries and your input. ☺

I have also tried VS 2019 build 16.10.0 (Prelease 1.0) and I have the same
issue as with 16.9.0

I have an old VS 2017 audacity.sln file which I have (meticulously)
upgraded/modified so that it runs on VS 2019 on my machine.  I do not have
the issue with this old upgraded solution file either for Release or for
Debug builds.

So, it seems that the issue appears when CMake is used to create the build,
but not with the solution file.  Perhaps there is some compiler default
that was changed in 16.9.0 that was somehow specified in the old solution
file.

We are not the first ones to see lrint problems.  See also,
https://github.com/InsightSoftwareConsortium/ITK/issues/1967

Later...

-  John

**Comment by JohnColket** [comment]
Thanks, James.  ditto.  😉
