### PR TITLE
Include portaudio.h in AudioIOBase.cpp

### PR DESCRIPTION
**Pull request by rrrapha**
This fixes the following compilation error on OpenBSD/clang (using 'system' version of portaudio):
```
/tmp/audacity-Audacity-2.4.2/src/AudioIOBase.cpp:80:47: error: member access into incomplete type 'const PaDeviceInfo'
   wxString infoName = wxSafeConvertMB2WX(info->name);
                                              ^
/tmp/audacity-Audacity-2.4.2/src/AudioIOBase.h:25:8: note: forward declaration of 'PaDeviceInfo'
struct PaDeviceInfo;
```

### CODE REVIEW

**Comment by rrrapha** [comment]
The problem has been introduced in https://github.com/audacity/audacity/commit/c84a2d295d7f0b9882f8e07f23d4bf371cd82461

**Comment by crsib** [comment]
This is fixed in different PR already
