### ISSUE TITLE
Failed to build with gcc 15.1.1 for ArchLinux

### ISSUE THREAD

**Issue by SpriteOvO** [audacity/audacity#8828]
### Bug description

I'm building this package for ArchLinux, the build log shows many errors like:

```

/build/audacity/src/audacity-Audacity-3.7.3/lib-src/libnyquist/nyquist/cmt/midifile.c:63:8: error: conflicting types for ‘Mf_header’; have ‘void (*)(void)’
   63 | void (*Mf_header)() = 0;
      |        ^~~~~~~~~
/build/audacity/src/audacity-Audacity-3.7.3/lib-src/libnyquist/nyquist/cmt/midifile.h:3:15: note: previous declaration of ‘Mf_header’ with type ‘void (*)(int,  int,  int)’
    3 | extern void (*Mf_header)(int,int,int);
      |               ^~~~~~~~~
```

Full build logs: [audacity-1:3.7.3-2-x86_64-build.log](https://github.com/user-attachments/files/20418448/audacity-1.3.7.3-2-x86_64-build.log)

### Steps to reproduce

1. Build script: [PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/audacity/-/blob/73be60316940642534697800ede9dbc4ad856c26/PKGBUILD).
2. Run `extra-x86_64-build`.

### Expected behavior

No error.

### Audacity Version

Audacity 3.7.3

### Operating system

Linux
