### ISSUE TITLE
Windows build broken in latest VisualStudio

### ISSUE THREAD

**Issue by SteveALee** [audacity/audacity#8326]
### Bug description

Here's a copy of the problem I tracked down [and reported](https://developercommunity.visualstudio.com/t/std::chrono-literals-broken/10856672)

\[regression\] \[worked-in:MSVC 19.42.34438.0\]  
Updating to latest VS Community (Version 17.13.1, MSVC 19.43.34808.0) my [ASIO build of Audacity](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b) breaks with an error with std:chrono literals

Error C2672: ‘std::this\_thread::sleep\_for’: no matching overloaded function found

in [this code](https://github.com/audacity/audacity/blob/7051a7a01873e26f1c8759edb87817da52e866b0/libraries/lib-project-file-io/DBConnection.cpp#L267-L273)

```  
{
         using namespace std::chrono;
         std::this\_thread::sleep\_for(50ms);
         pd->Pulse();
 }
  
  
```

The crazy ‘ms’ literal thing seems to be the issue,.

The [spec is clear this](https://en.cppreference.com/w/cpp/chrono/operator%22%22ms) should be OK

I tried opening the chrono\_literals namespace but it does not exist.

worked in MSVC 19.42.34438.0

? How do we download the old version of visual studio?  
? Why do I have to sign in - used VS without and want to share this report with upstream project/

### Steps to reproduce

- Install latest VisualStudio
- Try to build latest release (3.7.1) using dev env or my [ASIO build script](https://gist.github.com/SteveALee/da24c2be633340b8791066dd98eb5d0b)

### Expected behavior

Build without errors

### Actual behavior

```bash
C:\projects\audacity\libraries\lib-project-file-io\DBConnection.cpp(270,38): error C3688: invalid literal suffix 'ms';
literal operator or literal operator template 'operator ""ms' not found [C:\projects\audacity-asio\libraries\lib-projec
t-file-io\lib-project-file-io.vcxproj]
C:\projects\audacity\libraries\lib-project-file-io\DBConnection.cpp(270,28): error C2672: 'std::this_thread::sleep_for'
: no matching overloaded function found [C:\projects\audacity-asio\libraries\lib-project-file-io\lib-project-file-io.vc
xproj]
      C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\thread(222,10):
      could be 'void std::this_thread::sleep_for(const std::chrono::duration<_Rep,_Period> &)'

C:\projects\audacity\libraries\lib-project-file-io\DBConnection.cpp(531,64): error C3688: invalid literal suffix 'ms';
literal operator or literal operator template 'operator ""ms' not found [C:\projects\audacity-asio\libraries\lib-projec
t-file-io\lib-project-file-io.vcxproj]
C:\projects\audacity\libraries\lib-project-file-io\DBConnection.cpp(531,54): error C2672: 'std::this_thread::sleep_for'
: no matching overloaded function found [C:\projects\audacity-asio\libraries\lib-project-file-io\lib-project-file-io.vc
xproj]

```

### Audacity Version

Audacity 3.7.1

### Operating system

Windows

**Comment by SteveALee** [comment]
A work around provided by a user of the script:

![Image](https://github.com/user-attachments/assets/35bf080f-4662-45ce-9adc-ab78b669582a)

**Comment by kryksyh** [comment]
@SteveALee Thanks for letting us know, the build is fixed on `release-3.7.2` branch (which is in beta).

**Comment by DavidBailes** [comment]
@kryksyh . I still have this similar issue in ExportCL.cpp:
13>ExportCL.cpp
13>U:\audacity\modules\import-export\mod-cl\ExportCL.cpp(707,35): error C3688: invalid literal suffix 'ms'; literal operator or literal operator template 'operator ""ms' not found
13>U:\audacity\modules\import-export\mod-cl\ExportCL.cpp(707,25): error C2672: 'std::this_thread::sleep_for': no matching overloaded function found
13>    C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.43.34808\include\thread(222,10):
13>    could be 'void std::this_thread::sleep_for(const std::chrono::duration<_Rep,_Period> &)'
13>Done building project "mod-cl.vcxproj" -- FAILED.

**Comment by kryksyh** [comment]
@DavidBailes thanks! Fixed that too, could you pull `release-3.7.2` and try again?

**Comment by DavidBailes** [comment]
Confirmed fixed. Thanks.

**Comment by SteveALee** [comment]
> the build is fixed on release-3.7.2 branch (which is in beta).

Is that for published executables? If so i'll bump the ASIO build and hope its fixed.

**Comment by kryksyh** [comment]
@SteveALee It has not yet been released, so it does not have the tag `Audacity-3.7.2`, which is used in your script. You need to update the version to 3.7.2 (line 36), and 

`git clone -b Audacity-%AUDACITY_REL% ...`

to 

`git clone -b release-%AUDACITY_REL%`

after that, it should build just fine

**Comment by SteveALee** [comment]
Aw, thanks. I actually just kicked a build off with those very after looking at the branches and tags.

I don't know what I find more amazing. That you could specify things like 10ms which seem to ignore all typing, or that it broke in a MSVC release!
