### PR TITLE
Fixes to build with wxWidgets 3.1.6

### PR DESCRIPTION
**Pull request by imciner2**
wxWidgets 3.1.6 was just released, and while updating the Fedora package it was noted that Audacity couldn't compile. Here are two patches that fix errors found during the compilation on Fedora against wx 3.1.6. More information is available in the commit message of each of them.

(downstream bug https://bugzilla.redhat.com/show_bug.cgi?id=2072823).

- [X] I signed [CLA](https://www.audacityteam.org/cla/)
- [X] The title of the pull request describes an issue it addresses
- [X] If changes are extensive, then there is a sequence of easily reviewable commits
- [X] Each commit's message describes its purpose and effects
- [X] There are no behavior changes unnecessary for the stated purpose of the PR

Recommended:
- [X] Each commit compiles and runs on my machine without known undesirable changes of behavior

### CODE REVIEW

**Comment by imciner2** [comment]
@crsib who on the dev team would be good/available to review these changes to fix the build?

**Comment by crsib** [comment]
I'll try to do it sometime soon,

**Review by crsib — APPROVED** [review]

**Comment by imciner2** [comment]
@crsib thanks for merging this!

**Comment by VVD** [comment]
Same bug during build with wxWidgets 3.2.0 (just released):
```
/tmp/work/usr/ports/audio/audacity/work/audacity-Audacity-3.1.3/src/AudacityApp.cpp:1000:80: error: field of type 'wxString' has private constructor
   { wxLANGUAGE_USER_DEFINED, wxT("eu"), WL(0, SUBLANG_DEFAULT) wxT("Basque"), wxLayout_LeftToRight },
                                                                               ^
/usr/local/include/wx-3.2/wx/string.h:324:3: note: declared private here
  wxString(int);
  ^
1 error generated.
```
The commit https://github.com/audacity/audacity/pull/2776/commits/efc11c4ac50ac51cd71d4dcfa84e63b11000c3f5 look like 3.1.6 specific and need adaptation for 3.2.x.

**Comment by VVD** [comment]
Do wxCHECK_VERSION(x.y) work like ">= x.y"?
If so then the patch is correct for 3.2.
Will test now…

**Comment by VVD** [comment]
Build and work fine with patches and with wxWidgets 3.2.0.
