### PR TITLE
Add support for cross compilation targeting Windows

### PR DESCRIPTION
**Pull request by walisser**
In combination with pull #160, enables cross-compilation via mxe environment (build may fail without that commit).

Confirmed does not break build on Linux (ubuntu 16.04).

The commits prefixed with "cross-compile:" pertain to build scripts and configure tests etc needed for cross compilation and/or targeting mingw. Generally there are separate commits for each lib-src subdir unless the issue was global.

There are separate commits for the autotools-generated files (comment "autotools update" etc).

The other commits are to fix compilation errors on mingw, nothing major.

Other miscellaneous:
- adds --enable-openmp for compiling with new OpenMP code
- adds --std=gnu++11 instead of --std=c++11 as required by wxWidgets
- configuration test for wxWidgets "high dpi" patch
- cleaned up a few spots in configure.ac around other changes (cosmetics)

### CODE REVIEW

**Comment by walisser** [comment]
I think this will pass Travis now, the last fail was from outside commit. How can I kick off another build without changing anything?

**Comment by walisser** [comment]
I think this will pass Travis now, the last fail was from outside commit. How can I kick off another build without changing anything?

**Comment by Paul-Licameli** [comment]
I'm doing my own furious pushing of many fixes lately.  Could you please rebase this onto more recent master, at:

2bc9497dc2e2892c99c6e6e05491c59013d46e36

then do push -f to your fork again?  Be sure none of your changes conflict with mine.  I will wait to push again until after you.

**Comment by Paul-Licameli** [comment]
On closer examination, I see that you do very little under src/ , but you are doing much under lib-src.

So there will not be conflict with my work.  However, we may hesitate to take changes in lib-src, making our copies out of sync with the source projects.

I suggest you separate those parts that affect libnyquist and discuss with Roger Dannenberg whether the changes are acceptable upstream in the Nyquist project.

**Comment by walisser** [comment]
libnyquist commits submitted #187

**Comment by JamesCrook** [comment]
This IS a nice idea, and I appreciate the work that has gone into it.  It really needs discussion on audacity devel mailing list if it has to have a hope of being included.  

My question really is what do we gain by supporting cross compiling with mingw?  Why not compile and test on the actual relevant platform and bypass the extra complexity of cross compiling?  It seems like there is potentially a lot of ongoing support work to maintain and check support for cross compiling. 

So I have added flags that suggest we will reject/close this pull request soon.  Discussion on our mailing list could maybe change that.

**Comment by henricj** [comment]
On Sun, Oct 14, 2018 at 12:25:25PM -0700, Darrell Walisser wrote:
> OpenMP on windows was the whole reason for this - it's the only way to get the OpenMP spectrogram on windows. However, there isn't any interest in OMP besides myself, and too few places where it makes sense to use it. So on this point it is not worthwhile to keep it alive.

Have you tried installing Ubuntu from the Windows Store and
running Audacity for Linux that way?  One would need to run
X Windows as well (xming?).  It runs directly on the Windows
kernel so it doesn't require a VM with the memory overhead
that implies.

For the pie-in-the-sky future there should be a better
division between computation and the rest of the
application.  Explaining to someone why their CUDA DLL to
accelerate some fancy effect needs to include bits of
wxWidgets, PulseAudio, and bits to emulate parts of
Audacity's UI would be a little awkward (creating both
practical and licensing integration problems).  Likewise,
while something like FFT certainly needs a default
implementation inside Audacity, for maximum performance one
would generally want to use stuff designed and optimized for
the given system's hardware (be that an Intel AVX2 unit, an
AMD GPU, or whatever).  Furthermore, such GPU or even
distributed computation is almost certainly going to require
batching or streaming to get good performance from
high-throughput but also higher latency hardware.  All that
strongly implies a pluggable computation infrastructure of
some kind.

For C++ standard itself, one might look at the HPX and SYCL
projects to see where things might be headed.

> 
> In terms of gains for Audacity in general... probably zero. Again, I was probably the only person needing to do this. With a little more work, autotools could be used on every platform to replace MSVC/XCode, but I doubt anyone will want to do that even if it means less maintenance and support.
> 
> Ideally autotools would be replaced with something more modern and MSVC/XCode support could be dropped or generated from the other system.

For unifying the build, CMake is well supported on all of
Audacity's platforms.  Visual Studio can open and build
CMake projects directly.  It is also already supported by
wxWidgets, including for building for Windows.  CMake may
have its warts, but autotools bring a level of
complexity that renders it rather opaque to most.


CMake is also what Microsoft's package manager "vcpkg" uses
under the hood:
   https://docs.microsoft.com/en-us/cpp/vcpkg
